version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=*

volumes:
  sqlite_data: