# Generated by Django 5.1.2 on 2025-02-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_customuser_id_alter_customuser_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='siteBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_checkout', models.CharField(max_length=100, verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='saldo',
            field=models.CharField(blank=True, default=400, max_length=700, null=True),
        ),
    ]
