# Generated by Django 5.1.2 on 2025-02-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_sitebase_alter_customuser_id_alter_customuser_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_checkout', models.CharField(blank=True, max_length=500, null=True, verbose_name='link_checkout')),
            ],
        ),
        migrations.DeleteModel(
            name='siteBase',
        ),
    ]
